/// <reference types="trusted-types" />

import type { VistaDefaultCtrl, VistaCustomCtrl, VistaOpt, VistaImgIdx } from './types';
import { setImageStyles } from './utils';

// Optimized SVG icons - common attributes applied via CSS
const chevronLeft = `<svg viewBox="0 0 24 24"><path d="m15 18-6-6 6-6"/></svg>`;
const chevronRight = `<svg viewBox="0 0 24 24"><path d="m9 18 6-6-6-6"/></svg>`;
const zoomInIcon = `<svg viewBox="0 0 24 24"><circle cx="11" cy="11" r="8"/><line x1="21" x2="16.65" y1="21" y2="16.65"/><line x1="11" x2="11" y1="8" y2="14"/><line x1="8" x2="14" y1="11" y2="11"/></svg>`;
const zoomOutIcon = `<svg viewBox="0 0 24 24"><circle cx="11" cy="11" r="8"/><line x1="21" x2="16.65" y1="21" y2="16.65"/><line x1="8" x2="14" y1="11" y2="11"/></svg>`;
const closeIcon = `<svg viewBox="0 0 24 24"><path d="M18 6 6 18"/><path d="m6 6 12 12"/></svg>`;
const downloadIcon = `<svg viewBox="0 0 24 24"><path d="M12 15V3"/><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><path d="m7 10 5 5 5-5"/></svg>`;

let cachedPolicy: TrustedTypePolicy | null = null;
function getPolicy() {
  if (cachedPolicy) return cachedPolicy;

  if (!window.trustedTypes) {
    (window as any).trustedTypes = {
      createPolicy: (_name: string, rules: any) => rules,
    } as TrustedTypePolicyFactory;
  }

  cachedPolicy = window.trustedTypes!.createPolicy('vistaView-policy', {
    createHTML: (input: string) => input, // HTML is generated by us, not user input
    createScript: () => {
      throw new Error('Not implemented');
    },
    createScriptURL: () => {
      throw new Error('Not implemented');
    },
  });

  return cachedPolicy;
}

function createTrustedHtml(htmlString: string): DocumentFragment {
  const policy = getPolicy();
  const trustedHtml = policy.createHTML(htmlString);
  const template = document.createElement('template');
  (template as any).innerHTML = trustedHtml;
  const html = template.content;
  template.remove();
  return html;
}

export function vistaViewDownload(): VistaCustomCtrl {
  return {
    name: 'download',
    icon: downloadIcon,
    onClick: async (image: VistaImgIdx) => {
      const response = await fetch(image.src);
      const blob = await response.blob();
      const finalUrl = response.url; // This is the redirected URL
      const link = document.createElement('a');
      link.href = URL.createObjectURL(blob);
      link.download = finalUrl.split('/').pop()?.split('?')[0].split('#')[0] || 'download';
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
    },
  };
}

function convertControlToHtml(control: VistaDefaultCtrl | VistaCustomCtrl): string {
  if (typeof control === 'string') {
    switch (control) {
      case 'zoomIn':
        return `<button aria-label="Zoom In" class="vvw-zoom-in vvw-ui">${zoomInIcon}</button>`;
      case 'zoomOut':
        return `<button aria-label="Zoom Out" disabled class="vvw-zoom-out vvw-ui">${zoomOutIcon}</button>`;
      case 'close':
        return `<button aria-label="Close" class="vvw-close vvw-ui">${closeIcon}</button>`;
      case 'indexDisplay':
        return `<div class="vvw-index vvw-ui" aria-hidden="true"></div>`;
      case 'description':
        return `<div class="vvw-desc vvw-ui" role="status" aria-live="polite" aria-atomic="true"></div>`;
      default:
        console.warn(`Unknown default control: ${control}. Will return empty string.`);
        return '';
    }
  }
  return `<button aria-label="${control.description || control.name}" data-vvw-control="${control.name}">${control.icon}</button>`;
}

export function vistaViewItem(el: VistaImgIdx, positionalIndex?: number): HTMLDivElement {
  const div = document.createElement('div');
  div.className = 'vvw-item';
  div.dataset.vvwPos = `${positionalIndex !== undefined ? positionalIndex : ''}`;
  div.dataset.vvwIdx = el.index.toString();

  div.appendChild(
    createTrustedHtml(
      `<p class="vvw-img-err">Error loading image</p>
      <img class="vvw-img-lo" src="${el.thumb || el.src}" alt="${el.alt || ''}" />
      <img class="vvw-img-hi" src="${el.src}" alt="${el.alt || ''}" />`
    )
  );

  const lo = div.querySelector('img.vvw-img-lo') as HTMLImageElement;
  const hi = div.querySelector('img.vvw-img-hi') as HTMLImageElement;

  setImageStyles(el, hi, lo, positionalIndex === 0);

  return div;
}

export function vistaViewComponent({
  controls,
}: {
  controls: VistaOpt['controls'];
}): DocumentFragment {
  const mapCtrl = (arr?: (VistaDefaultCtrl | VistaCustomCtrl)[]) =>
    arr ? arr.map(convertControlToHtml).join('') : '';

  const html = createTrustedHtml(
    `<div class="vvw-root" id="vvw-root">
    <div class="vvw-container">
      <div class="vvw-bg"></div>
      <div class="vvw-image-container"></div>
      <div class="vvw-top-bar vvw-ui"><div>${mapCtrl(controls?.topLeft)}</div><div>${mapCtrl(controls?.topCenter)}</div><div>${mapCtrl(controls?.topRight)}</div></div>
      <div class="vvw-bottom-bar vvw-ui"><div>${mapCtrl(controls?.bottomLeft)}</div><div>${mapCtrl(controls?.bottomCenter)}</div><div>${mapCtrl(controls?.bottomRight)}</div></div>
      <div class="vvw-prev vvw-ui"><button aria-label="Previous">${chevronLeft}</button></div>
      <div class="vvw-next vvw-ui"><button aria-label="Next">${chevronRight}</button></div>
    </div>
    </div>`
  );

  return html;
}
