/// <reference types="trusted-types" />

import type { VistaDefaultCtrl, VistaExtension, VistaOpt } from './types';

// Optimized SVG icons - common attributes applied via CSS
const chevronLeft = `<svg viewBox="0 0 24 24"><path d="m15 18-6-6 6-6"/></svg>`;
const chevronRight = `<svg viewBox="0 0 24 24"><path d="m9 18 6-6-6-6"/></svg>`;
const zoomInIcon = `<svg viewBox="0 0 24 24"><circle cx="11" cy="11" r="8"/><line x1="21" x2="16.65" y1="21" y2="16.65"/><line x1="11" x2="11" y1="8" y2="14"/><line x1="8" x2="14" y1="11" y2="11"/></svg>`;
const zoomOutIcon = `<svg viewBox="0 0 24 24"><circle cx="11" cy="11" r="8"/><line x1="21" x2="16.65" y1="21" y2="16.65"/><line x1="8" x2="14" y1="11" y2="11"/></svg>`;
const closeIcon = `<svg viewBox="0 0 24 24"><path d="M18 6 6 18"/><path d="m6 6 12 12"/></svg>`;

let cachedPolicy: TrustedTypePolicy | null = null;
function getPolicy() {
  if (cachedPolicy) return cachedPolicy;

  if (!window.trustedTypes) {
    (window as any).trustedTypes = {
      createPolicy: (_name: string, rules: any) => rules,
    } as TrustedTypePolicyFactory;
  }

  cachedPolicy = window.trustedTypes!.createPolicy('vistaView-policy', {
    createHTML: (input: string) => input, // HTML is generated by us, not user input
    createScript: () => {
      throw new Error('Not implemented');
    },
    createScriptURL: () => {
      throw new Error('Not implemented');
    },
  });

  return cachedPolicy;
}

function createTrustedHtml(htmlString: string): DocumentFragment {
  const policy = getPolicy();
  const trustedHtml = policy.createHTML(htmlString);
  const template = document.createElement('template');
  (template as any).innerHTML = trustedHtml;
  const html = template.content;
  template.remove();
  return html;
}

function convertControlToHtml(control: VistaDefaultCtrl | VistaExtension): string {
  if (typeof control === 'string') {
    switch (control) {
      case 'zoomIn':
        return `<div class="vvw-ui"><button aria-label="Zoom In" class="vvw-zoom-in">${zoomInIcon}</button></div>`;
      case 'zoomOut':
        return `<div class="vvw-ui"><button aria-label="Zoom Out" disabled class="vvw-zoom-out">${zoomOutIcon}</button></div>`;
      case 'close':
        return `<div class="vvw-ui"><button aria-label="Close" class="vvw-close">${closeIcon}</button></div>`;
      case 'indexDisplay':
        return `<div class="vvw-index vvw-ui" aria-hidden="true"></div>`;
      case 'description':
        return `<div class="vvw-desc vvw-ui" role="status" aria-live="polite" aria-atomic="true"></div>`;
      default:
        console.warn(`Unknown default control: ${control}. Will return empty string.`);
        return '';
    }
  }

  // For extensions, just return the container structure
  return `<div class="vvw-ext vvw-ui" aria-label="${control.description || control.name}" data-vvw-control="${control.name}"></div>`;
}

export function vistaViewComponent({
  controls,
}: {
  controls: VistaOpt['controls'];
}): DocumentFragment {
  const mapCtrl = (arr?: (VistaDefaultCtrl | VistaExtension)[]) =>
    arr ? arr.map(convertControlToHtml).join('') : '';

  const html = createTrustedHtml(
    `<div class="vvw-root" id="vvw-root">
    <div class="vvw-container">
      <div class="vvw-bg"></div>
      <div class="vvw-image-container"></div>
      <div class="vvw-top-bar">
        <div>${mapCtrl(controls?.topLeft)}</div>
        <div>${mapCtrl(controls?.topCenter)}</div>
        <div>${mapCtrl(controls?.topRight)}</div>
      </div>
      <div class="vvw-bottom-bar">
        <div>${mapCtrl(controls?.bottomLeft)}</div>
        <div>${mapCtrl(controls?.bottomCenter)}</div>
        <div>${mapCtrl(controls?.bottomRight)}</div>
      </div>
      <div class="vvw-prev vvw-ui"><button aria-label="Previous">${chevronLeft}</button></div>
      <div class="vvw-next vvw-ui"><button aria-label="Next">${chevronRight}</button></div>
    </div>
    </div>`
  );

  // Populate extension containers with actual elements
  [
    ...(controls?.topLeft || []),
    ...(controls?.topCenter || []),
    ...(controls?.topRight || []),
    ...(controls?.bottomLeft || []),
    ...(controls?.bottomCenter || []),
    ...(controls?.bottomRight || []),
  ].forEach((ext) => {
    if (typeof ext !== 'string' && ext.control) {
      const container = html.querySelector(`[data-vvw-control="${ext.name}"]`);
      const el = ext.control();
      if (container && el) {
        container.appendChild(el);
      }
    }
  });

  return html;
}
