/// <reference types="trusted-types" />
import type { VistaViewElmProps } from './types';

export function getElmProperties(elm: HTMLElement): VistaViewElmProps {
  const s = getComputedStyle(elm);
  const pos = elm.getBoundingClientRect();
  return {
    objectFit: s.objectFit,
    borderRadius: s.borderRadius,
    objectPosition: s.objectPosition,
    overflow: s.overflow,
    top: pos.top,
    left: pos.left,
    width: pos.width,
    height: pos.height,
    naturalWidth: (elm as HTMLImageElement).naturalWidth,
    naturalHeight: (elm as HTMLImageElement).naturalHeight,
  };
}

let cachedPolicy: TrustedTypePolicy | null = null;
function getPolicy() {
  if (cachedPolicy) return cachedPolicy;

  if (!window.trustedTypes) {
    (window as any).trustedTypes = {
      createPolicy: (_name: string, rules: any) => rules,
    } as TrustedTypePolicyFactory;
  }

  cachedPolicy = window.trustedTypes!.createPolicy('vistaView-policy', {
    createHTML: (input: string) => input, // HTML is generated by us, not user input
    createScript: () => {
      throw new Error('Not implemented');
    },
    createScriptURL: () => {
      throw new Error('Not implemented');
    },
  });

  return cachedPolicy;
}

export function createTrustedHtml(htmlString: string): DocumentFragment {
  const policy = getPolicy();
  const trustedHtml = policy.createHTML(htmlString);
  const template = document.createElement('template');
  (template as any).innerHTML = trustedHtml;
  const html = template.content;
  template.remove();
  return html;
}

export function isNotZeroCssValue(value?: string): false | string | undefined {
  return (
    value && !/^0(px|%|r?em|vw|vh|vmin|vmax|cm|mm|in|pt|pc|ex|ch)?$/i.test(value.trim()) && value
  );
}

export function getFittedSize(img: HTMLImageElement): {
  width: number;
  height: number;
} {
  const style = window.getComputedStyle(img);
  const objectFit = style.objectFit || ''; // empty string in some old browsers

  // Rendered <img> size
  const { width: boxW, height: boxH } = img.getBoundingClientRect();

  // Natural image size
  const natW = img.naturalWidth;
  const natH = img.naturalHeight;

  // If object-fit is not supported → fallback to "fill" behavior
  if (!objectFit) {
    return { width: boxW, height: boxH };
  }

  // natural size missing (e.g., SVG, broken image)
  if (!natW || !natH) {
    return { width: boxW, height: boxH };
  }

  const imageAR = natW / natH;
  const boxAR = boxW / boxH;

  switch (objectFit) {
    case 'fill':
      return { width: boxW, height: boxH };

    case 'none':
      return { width: natW, height: natH };

    case 'contain':
      if (imageAR > boxAR) {
        return { width: boxW, height: boxW / imageAR };
      } else {
        return { width: boxH * imageAR, height: boxH };
      }

    case 'cover':
      if (imageAR < boxAR) {
        return { width: boxW, height: boxW / imageAR };
      } else {
        return { width: boxH * imageAR, height: boxH };
      }

    case 'scale-down': {
      // natural size
      const natural = { width: natW, height: natH };

      // contain size
      const contain =
        imageAR > boxAR
          ? { width: boxW, height: boxW / imageAR }
          : { width: boxH * imageAR, height: boxH };

      // pick the smaller of the two
      return contain.width <= natural.width && contain.height <= natural.height ? contain : natural;
    }
  }

  // Unknown or non-standard object-fit → fallback
  return { width: boxW, height: boxH };
}

export function getFullSizeDim(img: HTMLImageElement): {
  width: number;
  height: number;
} {
  const vw = window.innerWidth;
  const vh = window.innerHeight;

  const nw = img.naturalWidth;
  const nh = img.naturalHeight;

  if (!nw || !nh) {
    console.error('Error', img);
    throw new Error('Image natural dimensions are zero');
  }

  if (nw < vw && nh < vh) {
    // smaller than screen, no need to resize
    return {
      width: nw,
      height: nh,
    };
  }

  const imageAR = nw / nh;
  const screenAR = vw / vh;

  let width: number;
  let height: number;

  if (imageAR > screenAR) {
    // Image is wider than screen → constrain by width
    width = vw;
    height = vw / imageAR;
  } else {
    // Image is taller than screen → constrain by height
    height = vh;
    width = vh * imageAR;
  }

  return {
    width,
    height,
  };
}

export function getMaxMinZoomLevels(
  currentWidth: number,
  currentHeight: number
): {
  maxDiffX: number;
  minDiffY: number;
  maxDiffY: number;
  minDiffX: number;
} {
  const winHeight = window.innerHeight;
  const winWidth = window.innerWidth;
  const imageWidth = currentWidth;
  const imageHeight = currentHeight;
  const maxDiffX = Math.max(0, (imageWidth - winWidth) / 2) + winWidth / 2;
  const maxDiffY = Math.max(0, (imageHeight - winHeight) / 2) + winHeight / 2;
  const minDiffX = -maxDiffX;
  const minDiffY = -maxDiffY;

  return {
    maxDiffX,
    minDiffY,
    maxDiffY,
    minDiffX,
  };
}

export function clamp(value: number, min: number, max: number): number {
  return Math.min(Math.max(value, min), max);
}

export function limitPrecision(value: number, precision = 2): number {
  const factor = Math.pow(10, precision);
  return Math.round(value * factor) / factor;
}
