/// <reference types="trusted-types" />
import type { VistaViewElmProps } from './types';

export function getElmProperties(elm: HTMLElement): VistaViewElmProps {
  const s = getComputedStyle(elm);
  const pos = elm.getBoundingClientRect();
  return {
    objectFit: s.objectFit,
    borderRadius: s.borderRadius,
    objectPosition: s.objectPosition,
    overflow: s.overflow,
    top: pos.top,
    left: pos.left,
    width: pos.width,
    height: pos.height,
    naturalWidth: (elm as HTMLImageElement).naturalWidth,
    naturalHeight: (elm as HTMLImageElement).naturalHeight,
  };
}

let cachedPolicy: TrustedTypePolicy | null = null;
function getPolicy() {
  if (cachedPolicy) return cachedPolicy;

  if (!window.trustedTypes) {
    (window as any).trustedTypes = {
      createPolicy: (_name: string, rules: any) => rules,
    } as TrustedTypePolicyFactory;
  }

  cachedPolicy = window.trustedTypes!.createPolicy('vistaView-policy', {
    createHTML: (input: string) => input, // HTML is generated by us, not user input
    createScript: () => {
      throw new Error('Not implemented');
    },
    createScriptURL: () => {
      throw new Error('Not implemented');
    },
  });

  return cachedPolicy;
}

export function createTrustedHtml(htmlString: string): DocumentFragment {
  const policy = getPolicy();
  const trustedHtml = policy.createHTML(htmlString);
  const template = document.createElement('template');
  (template as any).innerHTML = trustedHtml;
  const html = template.content;
  template.remove();
  return html;
}

export function isNotZeroCssValue(value?: string): false | string | undefined {
  return (
    value && !/^0(px|%|r?em|vw|vh|vmin|vmax|cm|mm|in|pt|pc|ex|ch)?$/i.test(value.trim()) && value
  );
}

export function getFittedSize(img: HTMLImageElement): {
  width: number;
  height: number;
} {
  const style = window.getComputedStyle(img);
  const objectFit = style.objectFit || ''; // empty string in some old browsers

  // Rendered <img> size
  const { width: boxW, height: boxH } = img.getBoundingClientRect();

  // Natural image size
  const natW = img.naturalWidth;
  const natH = img.naturalHeight;

  // If object-fit is not supported → fallback to "fill" behavior
  if (!objectFit) {
    return { width: boxW, height: boxH };
  }

  // natural size missing (e.g., SVG, broken image)
  if (!natW || !natH) {
    return { width: boxW, height: boxH };
  }

  const imageAR = natW / natH;
  const boxAR = boxW / boxH;

  switch (objectFit) {
    case 'fill':
      return { width: boxW, height: boxH };

    case 'none':
      return { width: natW, height: natH };

    case 'contain':
      if (imageAR > boxAR) {
        return { width: boxW, height: boxW / imageAR };
      } else {
        return { width: boxH * imageAR, height: boxH };
      }

    case 'cover':
      if (imageAR < boxAR) {
        return { width: boxW, height: boxW / imageAR };
      } else {
        return { width: boxH * imageAR, height: boxH };
      }

    case 'scale-down': {
      // natural size
      const natural = { width: natW, height: natH };

      // contain size
      const contain =
        imageAR > boxAR
          ? { width: boxW, height: boxW / imageAR }
          : { width: boxH * imageAR, height: boxH };

      // pick the smaller of the two
      return contain.width <= natural.width && contain.height <= natural.height ? contain : natural;
    }
  }

  // Unknown or non-standard object-fit → fallback
  return { width: boxW, height: boxH };
}

export function getFullSizeDim(img: HTMLImageElement): {
  width: number;
  height: number;
} {
  const vw = window.innerWidth;
  const vh = window.innerHeight;

  const nw = img.naturalWidth;
  const nh = img.naturalHeight;

  if (!nw || !nh) {
    console.error('Error', img);
    throw new Error('Image natural dimensions are zero');
  }

  if (nw < vw && nh < vh) {
    // smaller than screen, no need to resize
    return {
      width: nw,
      height: nh,
    };
  }

  const imageAR = nw / nh;
  const screenAR = vw / vh;

  let width: number;
  let height: number;

  if (imageAR > screenAR) {
    // Image is wider than screen → constrain by width
    width = vw;
    height = vw / imageAR;
  } else {
    // Image is taller than screen → constrain by height
    height = vh;
    width = vh * imageAR;
  }

  return {
    width,
    height,
  };
}

export function getMaxMinZoomLevels(
  currentWidth: number,
  currentHeight: number
): {
  maxDiffX: number;
  minDiffY: number;
  maxDiffY: number;
  minDiffX: number;
} {
  const winHeight = window.innerHeight;
  const winWidth = window.innerWidth;
  const imageWidth = currentWidth;
  const imageHeight = currentHeight;
  const maxDiffX = Math.max(0, (imageWidth - winWidth) / 2) + winWidth / 2;
  const maxDiffY = Math.max(0, (imageHeight - winHeight) / 2) + winHeight / 2;
  const minDiffX = -maxDiffX;
  const minDiffY = -maxDiffY;

  return {
    maxDiffX,
    minDiffY,
    maxDiffY,
    minDiffX,
  };
}

export interface PinchGestureState {
  isActive: boolean;
  startDistance: number;
  currentDistance: number;
  scale: number;
  center: { x: number; y: number };
  direction: 'in' | 'out' | null;
}

export class PinchDetector {
  private pinchState: PinchGestureState = {
    isActive: false,
    startDistance: 0,
    currentDistance: 0,
    scale: 1,
    center: { x: 0, y: 0 },
    direction: null,
  };

  private element: HTMLElement;
  private onPinchStart?: (state: PinchGestureState) => void;
  private onPinchMove?: (state: PinchGestureState) => void;
  private onPinchEnd?: (state: PinchGestureState) => void;

  constructor(
    element: HTMLElement,
    onPinchStart?: (state: PinchGestureState) => void,
    onPinchMove?: (state: PinchGestureState) => void,
    onPinchEnd?: (state: PinchGestureState) => void
  ) {
    this.element = element;
    this.onPinchStart = onPinchStart;
    this.onPinchMove = onPinchMove;
    this.onPinchEnd = onPinchEnd;

    this.attachEventListeners();
  }

  private getTouchDistance(touches: TouchList): number {
    if (touches.length < 2) return 0;
    const touch1 = touches[0];
    const touch2 = touches[1];
    const dx = touch1.clientX - touch2.clientX;
    const dy = touch1.clientY - touch2.clientY;
    return Math.sqrt(dx * dx + dy * dy);
  }

  private getTouchCenter(touches: TouchList): { x: number; y: number } {
    if (touches.length < 2) return { x: 0, y: 0 };
    const touch1 = touches[0];
    const touch2 = touches[1];
    return {
      x: (touch1.clientX + touch2.clientX) / 2,
      y: (touch1.clientY + touch2.clientY) / 2,
    };
  }

  private onTouchStart = (e: TouchEvent) => {
    if (e.touches.length === 2) {
      e.preventDefault();
      this.pinchState.isActive = true;
      this.pinchState.startDistance = this.getTouchDistance(e.touches);
      this.pinchState.currentDistance = this.pinchState.startDistance;
      this.pinchState.scale = 1;
      this.pinchState.center = this.getTouchCenter(e.touches);
      this.pinchState.direction = null;
      this.onPinchStart?.(this.pinchState);
    }
  };

  private onTouchMove = (e: TouchEvent) => {
    if (this.pinchState.isActive && e.touches.length === 2) {
      e.preventDefault();
      this.pinchState.currentDistance = this.getTouchDistance(e.touches);
      this.pinchState.scale = this.pinchState.currentDistance / this.pinchState.startDistance;
      this.pinchState.center = this.getTouchCenter(e.touches);

      // Determine pinch direction based on scale
      if (this.pinchState.scale > 1.02) {
        this.pinchState.direction = 'out'; // Pinch out = zoom in
      } else if (this.pinchState.scale < 0.98) {
        this.pinchState.direction = 'in'; // Pinch in = zoom out
      }

      this.onPinchMove?.(this.pinchState);
    }
  };

  private onTouchEnd = (e: TouchEvent) => {
    if (this.pinchState.isActive && e.touches.length < 2) {
      this.onPinchEnd?.(this.pinchState);
      this.pinchState.isActive = false;
      this.pinchState.startDistance = 0;
      this.pinchState.currentDistance = 0;
      this.pinchState.scale = 1;
      this.pinchState.direction = null;
    }
  };

  private attachEventListeners(): void {
    this.element.addEventListener('touchstart', this.onTouchStart, { passive: false });
    this.element.addEventListener('touchmove', this.onTouchMove, { passive: false });
    this.element.addEventListener('touchend', this.onTouchEnd, { passive: false });
    this.element.addEventListener('touchcancel', this.onTouchEnd, { passive: false });
  }

  public cleanup(): void {
    this.element.removeEventListener('touchstart', this.onTouchStart);
    this.element.removeEventListener('touchmove', this.onTouchMove);
    this.element.removeEventListener('touchend', this.onTouchEnd);
    this.element.removeEventListener('touchcancel', this.onTouchEnd);
  }

  public isPinching(): boolean {
    return this.pinchState.isActive;
  }

  public getState(): PinchGestureState {
    return { ...this.pinchState };
  }
}
